fix: close() fails to write some bits
coherence/brook-go pull request #3
Opened 2020-10-31 03:29 UTC by cbrisebois

fix: close() and Octets() fail to write some bits when there are bits in the accumulator but there are not 4 octets left on the stream.  Now, it writes what it can according to the available space so we don't lose info.
feat: many, many more tests
refactor: some debugging and convenience features in the tests
feat: new DebugOctets in the outbit stream to access octets data without writing the accumulator.
refactor: update inbitstream to use notion of accumulator when dealing with masks and remove magic 32s everywhere and keep it aligned with outbitstream
feat: add Tell to inbitstream and fix the constructor so the value is set (was previously ignored)

2020-10-31 03:31 UTC, cbrisebois commented
I invited three reviews because of the amount of code changed and how I'm not fond of some of it.  I'll add comments on things I'd like closely reviewed and if possible someone (all?) should really make sure I'm not being dumb with the logic of the changes.  I think the tests are all bearing out (please check to make sure the tests aren't dumb) and I add them when I find an issue before I fix it so I can be sure the issue goes away, so I think they're solid.  All told, though, I'm really, really, new to Go and might be making dumb mistakes, so please be brutal with comments so I can learn.

2020-11-02 08:43 UTC, eriksvedang approved these changes

2020-11-02 09:25 UTC, rpadrela commented on src/inbitstream/inbitstreamimpl.go
> +const MaxFilter = 0xffffffff
Could potentially use const math.MaxUint32.

https://golang.org/pkg/math/#pkg-constants

2020-11-02 09:45 UTC, rpadrela commented on src/inbitstream/inbitstreamimpl.go
> +	return MaxFilter
Is the cast of 'count' to uint required? count is already a 'uint'.

The expression 'return (1 << count) - 1' returns 0xffffffff even for 'count' values over 'AccumulatorSize'. Examples:

count=30, mask=3fffffff
count=31, mask=7fffffff
count=32, mask=ffffffff
count=100, mask=ffffffff

Do we need the extra check?

2020-11-02 09:52 UTC, rpadrela commented on src/outbitstream/outbitstreamimpl.go
> +	return s.octetArray[0:octetCountWrittenTo], err
Should we try to access the 'octetArray' even if 'err' is not nil? Couldn't that lead to an out-of-range access? An out-of-range access will panic, I think.

2020-11-02 10:08 UTC, rpadrela commented on src/outbitstream/outbitstreamimpl.go
> +	return val
could add 'else if' to avoid the 2nd unnecessary check?

Could also be implemented like this: 'return math.Max(math.Min(val, max), min)'

2020-11-02 10:14 UTC, rpadrela commented on src/outbitstream/outbitstreamimpl.go
> +	return val
btw, there's a non-standard mathutil module that provides a clamp function, not sure about adding the extra dependency though...

2020-11-02 10:36 UTC, rpadrela commented on src/outbitstream/outbitstreamimpl.go
> +func (s *OutBitStreamImpl) writeAccumulatorToArray() error {
Is there a need for a return type here?

2020-11-02 10:36 UTC, rpadrela commented on src/outbitstream/outbitstreamimpl.go
> +	return s.octetArray[0:octetCountWrittenTo], err
Seems like writeAccumulatorToArray() always returns nil. Consider removing the return type and simplifying the code here.

2020-11-02 10:36 UTC, rpadrela requested changes
Left some minor comments but might be worth going through.

2020-11-02 19:21 UTC, merged